services:
  - type: web
    name: face-attendance
    env: python
    buildCommand: |
      echo "Clearing Poetry from path"
      rm -f pyproject.toml poetry.lock
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
