services:
  - type: web
    name: face-attendance-app
    env: python
    plan: free
    region: oregon
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    pullRequestPreviewsEnabled: true
